### ISSUE TITLE
Feature request - Auto increment a release radar extract album playlist

### ISSUE THREAD

**Issue by benoittgt** [enzsmn/spotify-album-extract#1]
Hello

First thanks a lot for this awesome project.

Every friday I connect to your app, go to Release Radar, extract to a new playlist, then on Spotify I take all songs for the newly created playlist and put them into a playlist "Release Radar - Album", then delete the playlist created called "Release Radar Album Album"

I would love to see the ability to keep in sync a playlist of extracted albums an his origin. One pain is the original source should only add new tracks and do not try to override already deleted songs in the extracted album playlist.

Rules:
 - When a track is added to a playlist, append new album's track to a specified playlist, do the sync every day at least.

🌮

**Comment by enzsmn** [comment]
Thanks for the feedback! I actually created this to use with my Release Radar as well, so we're in the same boat :)

I've been thinking about your idea and it does sound useful, but it would greatly increase the scope of this application, from a small frontend application to an application with a frontend and backend and scheduled jobs. So this is probably not something I'll start to build soon.

A smaller change I've been thinking of is to provide a way to add the selected albums to an existing playlist, saving you (and me) the step of selecting and copying all tracks in Spotify, adding them to another playlist, and deleting the new playlist.

**Comment by enzsmn** [comment]
The feature to add your selection to an existing playlist is now available.
Cheers!
